plugins {
	id 'net.fabricmc.fabric-loom' version '1.14-SNAPSHOT'
}

// Uncomment once the 26.1 patch is merged
// apply from: 'https://raw.githubusercontent.com/TerraformersMC/GradleScripts/2.7/ferry.gradle'


dependencies {
	minecraft "com.mojang:minecraft:$project.minecraft_version"

	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	implementation "eu.pb4:placeholder-api:${project.text_placeholder_api_version}"

	compileOnly "org.quiltmc:quilt-loader:$project.quilt_loader_version"
}

repositories {
	maven {
		name = 'TerraformersMC'
		url = 'https://maven.terraformersmc.com/'
	}

	maven {
		name = 'Quilt'
		url = 'https://maven.quiltmc.org/repository/release'
	}

	maven {
		name = 'Nucleoid'
		url = 'https://maven.nucleoid.xyz/'
	}
}